### ISSUE TITLE
ent2ml 일부 아이디 검색시 오류 발생

### ISSUE THREAD

**Issue by moxbt** [EntryDark/Ent2ml#18]
```
오류가 발생했습니다. :(
새로고침해도 계속 같은 오류가 발생하면
이 화면을 캡쳐해서
Issue 페이지에 올려주세요.

TypeError: Cannot read property 'getRgb' of null
```
([baboseojin 아이디](https://ent2.ml/baboseojin)) 검색 시 위 오류가 발생합니다.
정보 로드까지는 잘 안되는데 오류 메세지를 보아 배경색 변경에 오류가 발생하는 듯합니다.

**Comment by gnlow** [comment]
제보 감사합니다. 빨리 고치겠습니다.

**Comment by gnlow** [comment]
node-vibrant 모듈 문제인 것 같네요. 임시방편으로 색상값이 null일 경우 흰색이 기본으로 나오도록 했습니다.
