### ISSUE TITLE
이름이 긴 유저 처리

### ISSUE THREAD

**Issue by dn1t** [EntryDark/Ent2ml#8]
![image](https://user-images.githubusercontent.com/45326612/95033976-feb81680-06fa-11eb-8ff3-302d7a3decd9.png)

`font-size` 줄이기 또는 `text-overflow: ellipsis`

**Comment by john0817-he** [comment]
?

**Comment by john0817-he** [comment]
ㄷ

**Comment by gnlow** [comment]
![image](https://user-images.githubusercontent.com/27040628/95173140-415d1a00-07f3-11eb-8d01-f965cf21d527.png)
`font-size`를 자동 조정하도록 수정했습니다.
